#!/bin/sh
mkdir -p ../builds/linux64
cd ./source
gcc -std=gnu99 -Wall -g -I. ./main.c ./core/debug_print.c ./core/ensure.c ./platform/device.c ./platform/gl.c ./resources/resblob.c ./visual/texture.c -lX11 -lGL -o ../../builds/linux64/clover
