#!/bin/sh
mkdir -p ./temp
cd ./deps/common
clang -std=gnu99 -O2 -Wall -march=native -ffast-math -g -I . -c \
	-Wno-compare-distinct-pointer-types \
	-Wno-incompatible-pointer-types \
	-I ./chipmunk/include -I ./chipmunk/src \
	./unity.c \
	-o ../../temp/deps.o
