#ifndef REVOLC_GLOBAL_CFG_H
#define REVOLC_GLOBAL_CFG_H

// These options largely determine the memory usage of the engine

#define MAX_MODELENTITY_COUNT (1024*20)
#define MAX_DEBUG_DRAW_VERTICES (1024*50)
#define MAX_DEBUG_DRAW_INDICES (MAX_DEBUG_DRAW_VERTICES*3)
#define TEXTURE_ATLAS_WIDTH 4096
#define TEXTURE_ATLAS_LAYER_COUNT 4

#define MAX_NODE_COUNT (1024*20)
#define MAX_NODE_ROUTING_COUNT 8

#define MAX_RIGIDBODY_COUNT 1024
#define MAX_POLY_VERTEX_COUNT 8
#define MAX_POLY_COUNT 1024
#define MAX_CIRCLE_COUNT 1024
#define MAX_SHAPES_PER_BODY 4

#endif // REVOLC_GLOBAL_CFG_H
